install.packages("sf")
install.packages("leaflet")
install.packages("foreign")
install.packages("maptools")
install.packages("arsenal")
library("arsenal")
library("tidyr")
library("tidyverse")
library("sf")
library("leaflet")
library("foreign")
library("maptools")
rowsum <- read.dbf("Data/01_DCLS_ROWSUM.DBF")
rowsum1 <- read.dbf("Data/01_DCLS_ROWSUM1.DBF")
rowsum2 <- read.dbf("Data/01_DCLS_ROWSUM2.DBF")
rowsum3 <- read.dbf("Data/01_DCLS_ROWSUM3.DBF")

map <- st_read("Data/RoanokeTAZ.shp")

mean(rowsum$LNHBW)
mean(rowsum1$LNHBW)
mean(rowsum2$LNHBW)
mean(rowsum3$LNHBW)
n.diffs(comparedf(rowsum, rowsum3))
