---
title: "Resiliency Sample Calculations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
```


$$HighwayTime_{AM} =MW[1] = 1.55$$
$$HighwayDist = MW[2] = 0.72$$
$$Transit_{PK} = MW[3] = 0$$
$$MW[4] = (MW[2]/)*60$$
## Parameters ##
constants <- read_csv("Data/MC_Constants.csv")
coefficients <- read_csv("Data/MC_Coefficients.csv")

## HBW Utility Calculations ##
```{r HBW, echo= TRUE}
tibble


MW <- vector()
MW[1] <- 1.55
MW[2] <- 0.72
MW[3] <- 0
MW[4] <- (MW[2]/3)*60
MW[11] <- coefficients[1,3] * MW[1] + coefficients[5,3] * coefficients[19,3] * MW[2]
AutoUtility <- vector()
AutoUtility <- MW[11]
AutoUtility 

# <!-- The math works out for HBW Utility. I havent fixed the bug that causes the processed matrix to round differently, but it doesn't make a large difference in the long run -->
         
#MW[12] <- constants[3,3] + coefficients[9,3] * 20 *  MW[18] + coefficients[10,3] * 20 * MW[19]
#MW[12]
```

$$HBW_{Auto Utility} = -0.05422136$$

## Parameters ##

```{r Parameters, tidy = TRUE}
constants <- read_csv("Data/MC_Constants.csv")
coefficients <- read_csv("Data/MC_Coefficients.csv")
```
